# Generated by Django 4.2.7 on 2024-02-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_category_contactus_cart_flower_cartflower_flowerview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
